//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_hystory
    {
        public int ID { get; set; }
        public Nullable<int> ID_Employees { get; set; }
        public System.DateTime Entry_date { get; set; }
        public Nullable<System.DateTime> Finish_DATE { get; set; }
        public int Order_num_entry { get; set; }
        public Nullable<int> Order_num_finish { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
